# Generated by Django 5.1 on 2024-08-16 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_employees_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Participant',
            new_name='Participants',
        ),
        migrations.AlterField(
            model_name='employees',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='project.departments', verbose_name='Уникальный идентификатор отдела (FK)'),
        ),
    ]
