# Generated by Django 5.1 on 2024-08-16 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_rename_parent_project_id_projects_parent_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='parent_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.projects', verbose_name='Уникальный идентификатор головного проекта (FK)'),
        ),
    ]
